import "./logo.svg";
import "./logo-mb.svg";
import "./wallet-img.svg";
import "./wallet-img-1.svg"
import "./check-icon.svg";
import "./arrow-icon.svg";
import "./currency-icon.svg";
import "./safe-icon.svg";
import "./checkbox-icon.svg";
import "./ben-1-icon.svg";
import "./ben-2-icon.svg";
import "./ben-3-icon.svg";
import "./close-icon.svg";
import "./success-icon.svg";
import "./fail-icon.svg";
import "./phone-icon.svg";
import "./gosuslugi-icon.svg";
import "./arrow-gos.svg";
import "./arrowGreen.svg";
import './green-line.svg'
import "./camcom-wallet.svg";
import "./goldcup.svg"
import "./ring-icon.svg"
import "./medal.svg"
import "./clock-icon.svg"
import "./yandex-icon.svg"
import "./location-icon.svg"
import './dollar-icon.svg'
import './X-gray.svg'
import './X-green.svg'


