export let paymentHardCode = [
  {
    code: "sbp",
    desc: "Без данных карты, для РФ",
    icon: "icon-sbp",
    info: "Оплата картами банков РФ через мобильное приложение вашего банка, быстро и безопасно – без ввода данных карты. К системе подключено большинство банков РФ, включая Сбер, ВТБ, Альфа Банк, Тинькофф и прочие.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=SBP&prodamus_plugin=getcourse&plugin_version=",
    name: "Быстрый платеж",
  },
  {
    code: "ru",
    desc: "Выпущенная в РФ",
    icon: "icon-cards-ru",
    info: "Оплата банковской картой Visa, MasterCard, МИР и Maestro, включая кредитные карты. Для приема платежей мы используем надежное и безопасное платежное решение от Сбербанка. Процедура оплаты проста, деньги зачисляются мгновенно.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=AC&prodamus_plugin=getcourse&plugin_version=",
    name: "Банковская карта",
  },
  {
    code: "world",
    desc: "Выпущенная за рубежом",
    icon: "icon-cards-world",
    info: "После перехода к оплате будет выставлена сумма в тенге эквивалентная сумме заказа в рублях. Если Вы оплачиваете любой другой валютой, то ее конвертация в тенге будет происходить по курсу Вашего банка. Оплата доступна картами Visa, MasterCard и Maestro.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=ACf&prodamus_plugin=getcourse&plugin_version=",
    name: "Банковская карта",
  },
  {
    code: "kz",
    desc: "Выпущенная в Казахстане",
    icon: "icon-cards-kz",
    info: "После перехода к оплате будет выставлена сумма в тенге эквивалентная сумме заказа в рублях. Если Вы оплачиваете любой другой валютой, то ее конвертация в тенге будет происходить по курсу Вашего банка. Оплата доступна картами Visa, MasterCard и Maestro.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=ACkz&prodamus_plugin=getcourse&plugin_version=",
    name: "Банковская карта",
  },
  {
    code: "sbol",
    desc: "Перевод по номеру телефона",
    icon: "icon-sbol",
    info: "Вы можете оплатить заказ из личного кабинета Сбербанк Онлайн (в том числе с мобильного приложения). Для приема платежей мы используем надежное и безопасное платежное решение от Сбербанка. Процедура оплаты проста, деньги зачисляются мгновенно.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=sbol&prodamus_plugin=getcourse&plugin_version=",
    name: "Сбербанк Онлайн",
  },
  {
    code: "invoice",
    desc: "Безналичная оплата ИП / ООО",
    icon: "icon-invoice",
    info: "Вы можете оплатить заказ перечислением через банк со своего расчетного счета.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=invoice&prodamus_plugin=getcourse&plugin_version=",
    name: "Расчетный счет",
  },
  {
    code: "yoomoney",
    desc: "Электронный кошелек",
    icon: "icon-yoomoney",
    info: "Вы можете оплатить заказ с помощью электронного кошелька ЮMoney. Для приема платежей мы используем платежное решение от ЮMoney. Процедура оплаты проста и безопасна, деньги зачисляются мгновенно.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=PC&prodamus_plugin=getcourse&plugin_version=",
    name: "Кошелек ЮMoney",
  },
  {
    code: "qiwi",
    desc: "Электронный кошелек",
    icon: "icon-qiwi",
    info: "Вы можете оплатить заказ с электронного счета Qiwi. Для приема платежей мы используем платежное решение от ЮMoney. Процедура оплаты проста и безопасна, деньги зачисляются мгновенно.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=QW&prodamus_plugin=getcourse&plugin_version=",
    name: "Кошелек Qiwi",
  },
  {
    code: "terminals",
    desc: "Оплата через терминал",
    icon: "icon-terminals",
    info: "Вы можете оплатить заказ через обширную сеть платежных терминалов по всей стране, используя специальный код. Мы рекомендуем те терминалы, где нет комиссии: «Сбербанк», «Русский Стандарт»,  «Московский Кредитный Банк», терминалы «Мобил Элемент».",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=GP&prodamus_plugin=getcourse&plugin_version=",
    name: "Платежные терминалы",
  },
];

export const creditHardCode = [
  {
    id: "6w",
    desc: "Рассрочка на 6 недель",
    icon: "icon-prodamus",
    info: "Сумма заказа делится на 4 равные платежа, первый из которых оплачивается с карты сразу в момент оформления. Остальные 3 части спишутся автоматически с шагом в 2 недели. Без переплат и скрытых комиссий. Рассмотрение заявки до 3-х минут.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=installment&prodamus_plugin=getcourse&plugin_version=",
    name: "Частями от Продамус",
  },

  {
    id: "3m",
    desc: "Срок 3 месяца",
    icon: "icon-tinkoff",
    info: "Рассрочка от Тинькофф банка пользуется большой популярностью благодаря возможности оплачивать свои покупки без какой-либо переплаты. Процедура оформления проста, рассмотрение заявки от 3-х минут, подписание договора в режиме онлайн, сумма от 3500 до 200000 руб. Вам может быть предложено оформление КРЕДИТА от Тинькофф или МТС.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=installment_0_0_3&prodamus_plugin=getcourse&plugin_version=",
    name: "Тинькофф Рассрочка",
  },
  {
    id: "4m",
    desc: "Срок 4 месяца",
    icon: "icon-tinkoff",
    info: "Рассрочка от Тинькофф банка пользуется большой популярностью благодаря возможности оплачивать свои покупки без какой-либо переплаты. Процедура оформления проста, рассмотрение заявки от 3-х минут, подписание договора в режиме онлайн, сумма от 3500 до 200000 руб. Вам может быть предложено оформление КРЕДИТА от Тинькофф или МТС.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=installment_0_0_4&prodamus_plugin=getcourse&plugin_version=",
    name: "Тинькофф Рассрочка",
  },
  {
    id: "6m",
    desc: "Срок 6 месяцев",
    icon: "icon-tinkoff",
    info: "Рассрочка от Тинькофф банка пользуется большой популярностью благодаря возможности оплачивать свои покупки без какой-либо переплаты. Процедура оформления проста, рассмотрение заявки от 3-х минут, подписание договора в режиме онлайн, сумма от 3500 до 200000 руб. Вам может быть предложено оформление КРЕДИТА от Тинькофф или МТС.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=installment_0_0_6&prodamus_plugin=getcourse&plugin_version=",
    name: "Тинькофф Рассрочка",
  },
  {
    id: "10m",
    desc: "Срок 10 месяцев",
    icon: "icon-tinkoff",
    info: "Рассрочка от Тинькофф банка пользуется большой популярностью благодаря возможности оплачивать свои покупки без какой-либо переплаты. Процедура оформления проста, рассмотрение заявки от 3-х минут, подписание договора в режиме онлайн, сумма от 3500 до 200000 руб. Вам может быть предложено оформление КРЕДИТА от Тинькофф или МТС.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=installment_0_0_10&prodamus_plugin=getcourse&plugin_version=",
    name: "Тинькофф Рассрочка",
  },
  {
    id: "12m",
    desc: "Срок 12 месяцев",
    icon: "icon-tinkoff",
    info: "Рассрочка от Тинькофф банка пользуется большой популярностью благодаря возможности оплачивать свои покупки без какой-либо переплаты. Процедура оформления проста, рассмотрение заявки от 3-х минут, подписание договора в режиме онлайн, сумма от 3500 до 200000 руб. Вам может быть предложено оформление КРЕДИТА от Тинькофф или МТС.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=installment_0_0_12&prodamus_plugin=getcourse&plugin_version=",
    name: "Тинькофф Рассрочка",
  },
  {
    id: "24m",
    desc: "Срок 24 месяца",
    icon: "icon-tinkoff",
    info: "Рассрочка от Тинькофф банка пользуется большой популярностью благодаря возможности оплачивать свои покупки без какой-либо переплаты. Процедура оформления проста, рассмотрение заявки от 3-х минут, подписание договора в режиме онлайн, сумма от 3500 до 200000 руб. Вам может быть предложено оформление КРЕДИТА от Тинькофф или МТС.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=installment_0_0_24&prodamus_plugin=getcourse&plugin_version=",
    name: "Тинькофф Рассрочка",
  },
  {
    id: "credit20p",
    desc: "Ставка от 20%",
    icon: "icon-tinkoff",
    info: "Кредитная линия от Тинькофф банка пользуется большой популярностью благодаря возможности оплачивать свои покупки при отсутствии необходимой суммы на банковской карте. Процедура оформления проста, ставка от 20% , устанавливается персонально для каждого заемщика в зависимости от срока, кредитной истории и прочих условий, сумма от 3500 до 500000 руб.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=credit&prodamus_plugin=getcourse&plugin_version=",
    name: "Тинькофф Кредит",
  },
  {
    id: "da6m",
    desc: "Срок 6 месяцев",
    icon: "icon-vsegdada",
    info: "Оформление рассрочки на покупку товара.\r\nСумма от 3500 до 300000 &#8381;. Заявку рассматривают одновременно Совкомбанк и Kviku.\r\nВы сами выбираете между одобренными вариантами рассрочки.\r\nМаксимальная стоимость товара для оформления по Kviku 40000 р., Совкомбанк до 300000 р.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=vsegdada_installment_0_0_6&prodamus_plugin=getcourse&plugin_version=",
    name: "Всегда.Да Рассрочка",
  },
  {
    id: "da10m",
    desc: "Срок 10 месяцев",
    icon: "icon-vsegdada",
    info: "Оформление рассрочки на покупку товара.\r\nСумма от 3500 до 300000 &#8381;. Заявку рассматривают одновременно Совкомбанк и Kviku.\r\nВы сами выбираете между одобренными вариантами рассрочки.\r\nМаксимальная стоимость товара для оформления по Kviku 40000 р., Совкомбанк до 300000 р.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=vsegdada_installment_0_0_10&prodamus_plugin=getcourse&plugin_version=",
    name: "Всегда.Да Рассрочка",
  },
  {
    id: "da12m",
    desc: "Срок 12 месяцев",
    icon: "icon-vsegdada",
    info: "Оформление рассрочки на покупку товара.\r\nСумма от 3500 до 300000 &#8381;. Заявку рассматривают одновременно Совкомбанк и Kviku.\r\nВы сами выбираете между одобренными вариантами рассрочки.\r\nМаксимальная стоимость товара для оформления по Kviku 40000 р., Совкомбанк до 300000 р.",
    link: "https://mordasov.payform.ru/?invoice_id=95999fbb47742860391c1f82c84a5050&paylink=1&payment_method=vsegdada_installment_0_0_12&prodamus_plugin=getcourse&plugin_version=",
    name: "Всегда.Да Рассрочка",
  },
];

export const orders = [
  {
    key: 1,
    name: "Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 10000,
  },
  {
    key: 2,
    name: "Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 1000000,
  },
  {
    key: 3,
    name: "RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 10000,
  },
  {
    key: 4,
    name: "Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 220000,
  },
  {
    key: 5,
    name: "RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 112340,
  },
  {
    key: 6,
    name: "Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 10000,
  },
  {
    key: 7,
    name: "RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 10000,
  },
  {
    key: 8,
    name: "Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 10000,
  },
  {
    key: 9,
    name: "RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 1230,
  },
  {
    key: 10,
    name: "Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 0.1,
  },
  {
    key: 11,
    name: "RNB танцам в школе танцев Курс изКурс из 5 часовых занятий по RNB танцам в школе танцев",
    price: 10000,
  },
];

export const tabs = [
  {
    key: "auth",
    name: "Покупатель",
    title: "Покупатель",
    icon: "tab-auth-icon",
  },
  {
    key: "payment",
    name: "Оплата",
    title: "Оплата",
    icon: "tab-payment-icon",
  },
  {
    key: "credit",
    name: "Рассрочка",
    title: "Рассрочка",
    icon: "tab-credit-icon",
  },
  // {
  //   key: "order",
  //   name: "Заказ",
  //   title: "Заказ",
  //   icon: "tab-order-icon",
  // },
];

export const banks = [
  { code: "tinkoff", icon: "tinkoff-bank", name: "Тинькофф" },
  { code: "vtb", icon: "vtb-bank", name: "ВТБ" },
  { code: "raiffeisen", icon: "raiffeisen-bank", name: "Раффайзенбанк" },
  { code: "otkritie", icon: "otkritie-bank", name: "Открытие" },
  { code: "gazprom", icon: "gazprom-bank", name: "Газпромбанк" },
  { code: "rosbank", icon: "rosbank", name: "Росбанк" },
  { code: "other", icon: "other", name: "Другой банк" },
];
